# Generated by Django 3.2.17 on 2023-02-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.TextField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=32, unique=True, verbose_name='email')),
                ('phone', models.TextField(max_length=16)),
                ('alamat', models.TextField(max_length=128)),
                ('poin', models.IntegerField(default=0)),
                ('foto', models.TextField(max_length=128)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updateAt', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
                ('is_adminDesa', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_superAdmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
