# Generated by Django 4.1.6 on 2023-02-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_desaAdmin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='is_superAdmin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_superuser',
            new_name='is_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
