# Generated by Django 4.1.6 on 2023-02-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.TextField(default='123')),
                ('id_mesin', models.TextField(default='123')),
                ('volume', models.IntegerField(blank=True)),
                ('poin', models.IntegerField(blank=True)),
                ('jenis', models.TextField(blank=True)),
                ('waktuTransaksi', models.TextField(default=datetime.date(2023, 2, 7))),
                ('cretedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
