# Generated by Django 3.2.17 on 2023-02-08 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.TextField(default='123')),
                ('id_mesin', models.TextField(default='123')),
                ('volume', models.IntegerField(blank=True)),
                ('poin', models.IntegerField(blank=True)),
                ('jenis', models.TextField(blank=True)),
                ('waktuTransaksi', models.DateField(default=django.utils.timezone.now)),
                ('cretedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
