# Generated by Django 4.1.6 on 2023-02-05 08:58

import APIproduk.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('stok', models.IntegerField()),
                ('keterangan', models.CharField(max_length=128)),
                ('id_mesin', models.CharField(max_length=128)),
                ('gambar', models.CharField(max_length=128)),
                ('poin', models.IntegerField()),
                ('penukaran', djongo.models.fields.EmbeddedField(model_container=APIproduk.models.Penukaran)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('kategori', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='APIproduk.kategori')),
            ],
        ),
    ]
