# Generated by Django 3.2.17 on 2023-02-09 10:46

import APIproduk.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penukaran',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_pengguna', models.CharField(max_length=128)),
                ('kode', models.CharField(default='xxx', max_length=16)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('selesai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('stok', models.IntegerField()),
                ('keterangan', models.CharField(max_length=128)),
                ('id_mesin', models.CharField(max_length=128)),
                ('gambar', models.CharField(max_length=128)),
                ('harga', models.IntegerField()),
                ('kategori', models.CharField(default='', max_length=200)),
                ('penukaran', djongo.models.fields.ArrayField(default=[], model_container=APIproduk.models.Penukaran)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
