# Generated by Django 4.1.6 on 2023-02-05 15:16

import APIproduk.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('APIproduk', '0002_alter_produk_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='penukaran',
            field=djongo.models.fields.ArrayField(model_container=APIproduk.models.Penukaran, null=True),
        ),
    ]
