# Generated by Django 3.2 on 2023-02-06 05:34

import APIproduk.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('APIproduk', '0003_alter_produk_penukaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penukaran',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_pengguna', models.CharField(max_length=128)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='penukaran',
            field=djongo.models.fields.ArrayField(default=[], model_container=APIproduk.models.Penukaran),
        ),
    ]
