# Generated by Django 3.2 on 2023-02-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIproduk', '0004_auto_20230206_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='penukaran',
            name='kode',
            field=models.CharField(default='xxx', max_length=16),
        ),
        migrations.AddField(
            model_name='penukaran',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='penukaran',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
